// Users Actions
export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const USER_DESCRIPTION = 'USER_DESCRIPTION';

// Movies Actions
export const FETCH_MOVIES_ORIGINAL_NETFLIX = "FETCH_MOVIES_ORIGINAL_NETFLIX";
export const FETCH_MOVIES_TRADING_NOW = "FETCH_MOVIES_TRADING_NOW";
export const FETCH_MOVIES_TOP_RATED = "FETCH_MOVIES_TOP_RATED";
export const FETCH_MOVIES_ACTION = "FETCH_MOVIES_ACTION";
export const FETCH_MOVIES_COMEDY = "FETCH_MOVIES_COMEDY";
export const FETCH_MOVIES_HORROR = "FETCH_MOVIES_HORROR";
export const FETCH_MOVIES_ROMANCE = "FETCH_MOVIES_ROMANCE";
export const FETCH_MOVIES_DOCUMENTAL = "FETCH_MOVIES_DOCUMENTAL";